spring:
  application:
    name: "demo"

  # MySQL Database 설정
  datasource:
    url: jdbc:mysql://localhost:3306/bdd_practice?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false

# Springdoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    use-root-path: false

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace